# SonarQube / SonarCloud Project Configuration
sonar.organization=bh-gaur
sonar.projectKey=bh-gaur_DevSecOps-learn
sonar.projectName=DevSecOps-learn
sonar.sources=demo-app
sonar.tests=demo-app/tests
sonar.python.coverage.reportPaths=demo-app/coverage.xml
sonar.exclusions=**/tests/**,**/.venv/**
